const graphConfig = {
    "automaticRearrangeAfterDropNode": true,
    "collapsible": false,
    "directed": true,
    "focusAnimationDuration": 0.75,
    "focusZoom": 1,
    "height": 800,
    "highlightDegree": 2,
    "highlightOpacity": 0.2,
    "linkHighlightBehavior": true,
    "maxZoom": 12,
    "minZoom": 0.05,
    "nodeHighlightBehavior": true,
    "panAndZoom": false,
    "staticGraph": false,
    "staticGraphWithDragAndDrop": false,
    "width": 800,
    "d3": {
        "alphaTarget": 0.05,
        "gravity": -250,
        "linkLength": 200,
        "linkStrength": 1,
        "disableLinkForce": false
    },
    "node": {
        "color": "#d3d3d3",
        "fontColor": "black",
        "fontSize": 10,
        "fontWeight": "normal",
        "highlightColor": "red",
        "highlightFontSize": 14,
        "highlightFontWeight": "bold",
        "highlightStrokeColor": "red",
        "highlightStrokeWidth": 1.5,
        "mouseCursor": "grab",
        "opacity": 0.9,
        "renderLabel": true,
        "size": 200,
        "strokeColor": "none",
        "strokeWidth": 1.5,
        "symbolType": "square",
        "labelPosition" : 'bottom'
    },
    "link": {
        "color": "lightgray",
        "fontColor": "black",
        "fontSize": 8,
        "fontWeight": "normal",
        "highlightColor": "#FFBB01",
        "highlightFontSize": 8,
        "highlightFontWeight": "normal",
        "labelProperty": "label",
        "mouseCursor": "pointer",
        "opacity": 1,
        "renderLabel": false,
        "semanticStrokeWidth": true,
        "strokeWidth": 3,
        "markerHeight": 6,
        "markerWidth": 6
    }
}

export default graphConfig